#Matrices with one initial value
m <- matrix(0, nrow=10, ncol=5)
#Matrices with one character value
m <- matrix('a', nrow=10, ncol=5)
#Matrices initialized with a vector of elements with as many elements as the total number of matrix cells
m <- matrix(1:50, nrow=10, ncol=5)
#Matrices initialized with a smaller vector than the number of total elements
m1 <- matrix(1:10, nrow=10, ncol=5)
m2 <- matrix(1:10, nrow=10, ncol=5, byrow=TRUE)
#Matrices initialized with a vector that cannot be divided exactly with the total number of elements
m1 <- matrix(1:9, nrow=10, ncol=5)
## Warning in matrix(1:9, nrow = 10, ncol = 5): data length [9] is not a sub-
## multiple or multiple of the number of rows [10]
#Vectors
#Subsetting with negative indexes
v <- c(1,2,3)
v[-c(1,3)]
## [1] 2
#Subsetting with logical vectors
#Here the logical vector should be the same length, or to be divided exactly with the vector that we want to subset

v <- seq (1, 100, 2)
lv <- c(T,F)
v[lv]
##  [1]  1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89
## [24] 93 97
#Named vectors
v <- c(1,2,3)
names(v) <- c('a', 'b', 'c')

v[1]
## a 
## 1
v['b']
## b 
## 2
#This means that vectors can be also used as hashes



#Example with named vectors
#Constructing the complementary DNA strand
alphabet <- c('A', 'C', 'G', 'T')
names(alphabet) <- c('T', 'G', 'C', 'A')

dna <- sample(alphabet, 1000, TRUE)
compDNA <- alphabet[dna]





paste(dna, collapse='')


## [1] "GTTGTATAGGCAAAAAGTTCTGAGGCGGAGATAGCCGAAACCACGAACGCACAGTCGAATGTTCTTTCGCCTCCTACACGCCGCAGACGCCGCACTCGGCATGCGTCCCCCAAAACCATCCGTTCGCGAGCAGGTGCCTTAGTTATACCCAACTGTGATCGCACGCTTCCACTTCGCATCCAGCTGCTAAAAGGGCACTCCCTGTCGGCCAAATAACGTTAGGGCTCGGGCCGAGAGCGTGCTCTCTTTTTTGCGATATTAGGGCGGCTTCATGCTCTTGTGATCTGCATTTATCGCTGCCATACTGCTTACTCCCCTGCAGCGGTAGTGTGGTATTTGTGAGAAACTCTCACTATGATGAGGGCAAGAACATCTGTTCTTAGTCTGGCCGACGTAGAAAATGACCGTGTTACGGAATAACTCTCATTGGTTTCGAAACGCGAACGACGGGGATGCACACCCTATCTTCTAATCTCGGCGCTCAGATTTTACCGACACAATCACGCGGTACCCATTCCTAGGATGTCTACGCTAGAGTATCTGGTCCTGAGTCAGGGAGGTATGGCATGAACCCAGGCAGTTGCATCAGAATCTTACCTGCATGCTCCGGCACATTAAGCGATGCTTTAAGAACATTCCCGATCGGAGACAATGATGCGCTGAACCAAATTCTGATCCACTACTGTACCGATCAGAGGAGCCATAAACCAGAATCCGCGGGGCTTAATGTTAACTCAAAACGTTAACGCTCATTTATCCGAGGCTCAAGTTGCGCTAAGGTGAGTACGCGTCAATGAATGTTTACTGTCACCAGGTAATGTTCTAGACAGCAGAATCCGTAGCTGTTACTCGTATTGTGGCATAGGCCGCCCAACCCACATTCATAGCGGTATACACTCCCCCCTCCATACCACTTGGCCGAACGTTAAACGAGCAGCACGTGAGTTCCCGTACCTCTTTTCGTGTTGCATCGTCAACATATGGTTCGATGTCTCCTCAC"





paste(compDNA, collapse='')




## [1] "CAACATATCCGTTTTTCAAGACTCCGCCTCTATCGGCTTTGGTGCTTGCGTGTCAGCTTACAAGAAAGCGGAGGATGTGCGGCGTCTGCGGCGTGAGCCGTACGCAGGGGGTTTTGGTAGGCAAGCGCTCGTCCACGGAATCAATATGGGTTGACACTAGCGTGCGAAGGTGAAGCGTAGGTCGACGATTTTCCCGTGAGGGACAGCCGGTTTATTGCAATCCCGAGCCCGGCTCTCGCACGAGAGAAAAAACGCTATAATCCCGCCGAAGTACGAGAACACTAGACGTAAATAGCGACGGTATGACGAATGAGGGGACGTCGCCATCACACCATAAACACTCTTTGAGAGTGATACTACTCCCGTTCTTGTAGACAAGAATCAGACCGGCTGCATCTTTTACTGGCACAATGCCTTATTGAGAGTAACCAAAGCTTTGCGCTTGCTGCCCCTACGTGTGGGATAGAAGATTAGAGCCGCGAGTCTAAAATGGCTGTGTTAGTGCGCCATGGGTAAGGATCCTACAGATGCGATCTCATAGACCAGGACTCAGTCCCTCCATACCGTACTTGGGTCCGTCAACGTAGTCTTAGAATGGACGTACGAGGCCGTGTAATTCGCTACGAAATTCTTGTAAGGGCTAGCCTCTGTTACTACGCGACTTGGTTTAAGACTAGGTGATGACATGGCTAGTCTCCTCGGTATTTGGTCTTAGGCGCCCCGAATTACAATTGAGTTTTGCAATTGCGAGTAAATAGGCTCCGAGTTCAACGCGATTCCACTCATGCGCAGTTACTTACAAATGACAGTGGTCCATTACAAGATCTGTCGTCTTAGGCATCGACAATGAGCATAACACCGTATCCGGCGGGTTGGGTGTAAGTATCGCCATATGTGAGGGGGGAGGTATGGTGAACCGGCTTGCAATTTGCTCGTCGTGCACTCAAGGGCATGGAGAAAAGCACAACGTAGCAGTTGTATACCAAGCTACAGAGGAGTG"
